### ISSUE TITLE
代码有误提醒

### ISSUE THREAD

**Issue by Kingze-future** [yanyueliu/Cell_Transmission_Model_Python#1]
你好，我翻阅了您上传的代码，发现了其中两处错误，我想提醒您一下，请修正如何？
1.isterSection函数未定义，位于50行
2.格式错误，位于349行，其中.appedn，您写成了a.ppend

**Comment by yanyueliu** [comment]
感谢你的提醒。
第50行的功能是考虑未来增加交叉口相关内容的，在上次提交的时候删掉了interSection类，但是没有删掉其他部分对应的代码。我会删除这部分内容。
第349行的错误我没有找到。

**Comment by Kingze-future** [comment]
多谢你的回复，你修改之后，没问题了，至于349行的错误，我看了看，没错误，应该是我自己这边的错误。

**Comment by Kingze-future** [comment]
你好，



您的BPR_X;
NETWORK_PHOENIX;
PLOT_QK分别是什么功能啊？
我当时COPY时并未发现这三个。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanyueliu/Cell_Transmission_Model_Python"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 下午5:26
收件人:&nbsp;"yanyueliu/Cell_Transmission_Model_Python"<Cell_Transmission_Model_Python@noreply.github.com&gt;;
抄送:&nbsp;"唐吉诃德与何则"<1280158385@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yanyueliu/Cell_Transmission_Model_Python] 代码有误提醒 (#1)





 
感谢你的提醒。
 第50行的功能是考虑未来增加交叉口相关内容的，在上次提交的时候删掉了interSection类，但是没有删掉其他部分对应的代码。我会删除这部分内容。
 第349行的错误我没有找到。

**Comment by yanyueliu** [comment]
这些功能暂时不便透露，等相关论文发表后会相应增加说明，并不影响主程序的使用。

**Comment by Kingze-future** [comment]
好的，多谢你的回复。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yanyueliu"<notifications@github.com&gt;; 
发送时间: 2020年11月16日(星期一) 晚上6:53
收件人: "yanyueliu/Cell_Transmission_Model_Python"<Cell_Transmission_Model_Python@noreply.github.com&gt;; 
抄送: "唐吉诃德与何则"<1280158385@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yanyueliu/Cell_Transmission_Model_Python] 代码有误提醒 (#1)





 
这些功能暂时不便透露，等相关论文发表后会相应增加说明，并不影响主程序的使用。
